#!/usr/bin/env bash

install() {
  info
  info 'Define method install and use library function link'
  info 'to create symlinks to your configuration files.'
  info
  info 'Example:'
  info
  info 'function install() {'
  info '  link .bashrc ~/.bashrc'
  info '}'
  info
  fail 'You need to define your own install function!'
}

#                 Do not alter bootstrap code below this line                 #
# --------------------------------------------------------------------------- #

__cache_directory() {
  local directory="${XDG_CACHE_HOME:-$HOME/.cache}/lnkr"
  mkdir -p "$directory" &>/dev/null && echo "$directory"
}

__latest_version() {
  local cache="$(__cache_directory)/latest"
  local cache_age="$(($(date +%s) - $(stat -c %Y "$cache" 2>&- || echo '0')))"
  if [ "$cache_age" -le 3600 ]; then
    head -n 1 "$cache" 2>&-
  else
    local url='https://api.github.com/repos/usommerl/lnkr/releases/latest'
    local response="$( (curl -Lfs "$url" || wget -qO - "$url") 2>&- )"
    local tag_name="$(echo "$response" | grep 'tag_name' | cut -d '"' -f 4)"
    echo "$tag_name" | tee "$cache"
  fi
}

__determine_version() {
  local lockfile='lnkr.lock'
  local locked_version="$(head -n 1 "$lockfile" 2>&-)"
  echo "${locked_version:-$(__latest_version)}" | tee "$lockfile"
}

__bootstrap() {
  local src='lnkr_lib.sh'
  local ver="$(__determine_version)"
  local lib="$(__cache_directory)/${src/%.sh/_$ver.sh}"
  local url="https://raw.githubusercontent.com/usommerl/lnkr/$ver/$src"
  [ ! -e "$lib" ] && (curl -Lfso "$lib" "$url" || wget -qO "$lib" "$url") 2>&-
  [ -e "$lib" ] && source "$lib" "$@"
  echo 'Bootstrap failed'; exit 1
}

cd "$(dirname "$(readlink -f "$0")")" && __bootstrap "$@"
