#!/usr/bin/env bash

function install() {
  info
  info 'Define method install and use library function link'
  info 'to create symlinks to your configuration files.'
  info
  info 'Example:'
  info
  info 'function install() {'
  info '  link .bashrc ~/.bashrc'
  info '}'
  info
  fail 'You need to define your own install function!'
}

# ----------------------------------- >8 ---------------------------------------
# Do not touch the line above and do not insert code after this line.
# The functions below are required to bootstrap the lnkr library.

__cache_directory() {
  local directory="${XDG_CACHE_HOME:-$HOME/.cache}/lnkr"
  mkdir -p "$directory" &>/dev/null && printf "%s" "$directory"
}

__latest_version() {
  local cache="$(__cache_directory)/latest"
  local difference="$(($(date +%s) - $(stat -c %Y "$cache" 2>&- || printf '0')))"
  local url='https://api.github.com/repos/usommerl/lnkr/releases/latest'
  local tag_name="(curl -Lfs $url || wget -qO - $url) 2>&- | grep 'tag_name'"
  if [ "$difference" -le 3600 ]; then
    printf "%s" "$(head -n 1 "$cache" 2>&-)"
  else
    printf "%s" "$(eval "$tag_name"  | cut -d '"' -f 4)" | tee "$cache"
  fi
}

__determine_version() {
  local lockfile='lnkr.lock'
  local locked_version="$(head -n 1 "$lockfile" 2>&-)"
  printf "%s" "${locked_version:-$(__latest_version)}" | tee "$lockfile"
}

__bootstrap() {
  local src='lnkr_lib.sh'
  local ver="$(__determine_version)"
  local lib="$(__cache_directory)/${src/%.sh/_$ver.sh}"
  local url="https://raw.githubusercontent.com/usommerl/lnkr/$ver/$src"
  [ ! -e "$lib" ] && (curl -Lfso "$lib" "$url" || wget -qO "$lib" "$url") 2>&-
  [ -e "$lib" ] && source "$lib" "$@"
  printf 'Bootstrap failed\n'; exit 1
}

cd "$(dirname "$(readlink -f "$0")")" && __bootstrap "$@"
